manager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("tasks.urls", namespace="tasks")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tasks/urls.py
from django.urls import path

from .views import (
    index,
    TagListView,
    TaskCreate,
    TaskUpdate,
    TaskDelete,
    TagCreate,
    TagUpdate,
    TagDelete,
    TaskUpdateCompletionView
)

urlpatterns = [
    path("", index, name="index"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreate.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdate.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDelete.as_view(), name="tag-delete"),
    path("tasks/create/", TaskCreate.as_view(), name="task-create"),
    path("tasks/<int:pk>/update/", TaskUpdate.as_view(), name="task-update"),
    path("tasks/<int:pk>/delete/", TaskDelete.as_view(), name="task-delete"),
    path(
        "tasks/<int:pk>/toggle/",
        TaskUpdateCompletionView.as_view(),
        name="task-toggle"
    )
]

app_name = "tasks"

tasks/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=63)

    def __str__(self) -> str:
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=255)
    datetime = models.DateTimeField(auto_now_add=True)
    deadline = models.DateField(null=True, blank=True)
    is_completed = models.BooleanField()
    tags = models.ManyToManyField(
        Tag,
        related_name="tasks"
    )

tasks/forms.py
from django import forms

from .models import Tag, Task


class DateInput(forms.DateInput):
    input_type = "date"


class TaskForm(forms.ModelForm):
    content = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Content*",
                                      "style": "padding: 10px"}),
        label=""
    )
    is_completed = forms.BooleanField(required=False)
    deadline = forms.DateTimeField(
        widget=DateInput(attrs={"style": "padding: 10px"})
    )
    tags = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        queryset=Tag.objects.all()
    )

    class Meta:
        model = Task
        fields = "__all__"


class TagForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Name*",
                                      "style": "padding: 10px"}),
        label=""
    )

    class Meta:
        model = Tag
        fields = "__all__"

task_list/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from .models import Task, Tag
from .forms import TaskForm, TagForm


def index(request):
    context = {
        "tasks": Task.objects.prefetch_related("tags"),
    }
    return render(request, "tasks/index.html", context=context)


def toggle_complete_task(request, pk):
    task = Task.objects.get(pk=pk)
    if task.is_completed:
        task.is_completed = False
    else:
        task.is_completed = True
    task.save()
    return HttpResponseRedirect(reverse_lazy(
        "tasks:index"
    ))


class TagListView(generic.ListView):
    model = Tag


class TagCreate(generic.CreateView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy("tasks:tag-list")


class TagUpdate(generic.UpdateView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy("tasks:tag-list")


class TagDelete(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("tasks:tag-list")


class TaskCreate(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("tasks:index")


class TaskUpdate(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("tasks:index")


class TaskDelete(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("tasks:index")

tasks/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic

from .models import Task, Tag
from .forms import TaskForm, TagForm


def index(request):
    context = {
        "tasks": Task.objects.prefetch_related("tags"),
    }
    return render(request, "tasks/index.html", context=context)


class TagListView(generic.ListView):
    model = Tag


class TagCreate(generic.CreateView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy("tasks:tag-list")


class TagUpdate(generic.UpdateView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy("tasks:tag-list")


class TagDelete(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("tasks:tag-list")


class TaskCreate(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("tasks:index")


class TaskUpdate(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("tasks:index")


class TaskUpdateCompletionView(generic.UpdateView):
    model = Task
    fields = []

    def post(self, request, *args, **kwargs):
        task = get_object_or_404(Task, id=kwargs["pk"])
        task.is_completed = not task.is_completed
        task.save()
        return redirect("tasks:index")


class TaskDelete(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("tasks:index")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>
    Task Manager
  </title>
  {% load static %}
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <!-- CSS Files -->
  <link id="pagestyle" href="{% static 'css/styles.css' %}" rel="stylesheet" />

</head>
<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3">
      {% block sidebar %}
        {% include 'includes/sidebar.html' %}
      {% endblock sidebar %}
    </div>
    <div class="col-sm-9">
      {% block content %}{% endblock content %}
    </div>
  </div>
</div>

</body>
</html>

templates/includes/sidebar.html
<ul class="list-group mt-6 col-md-10">
  <li class="list-group-item py-3">
    <a href="{% url 'tasks:index' %}">Home</a>
  </li>
  <li class="list-group-item py-3">
    <a href="{% url 'tasks:tag-list' %}">Tags</a>
  </li>
</ul>

templates/tasks/index.html
{% extends "base.html" %}

{% block content %}
  <h1 class="mb-5 mt-6 text-secondary d-flex">TODO list
    <a class="btn bg-gradient-info mt-2 mx-auto" href="{% url 'tasks:task-create' %}">Add task</a>
  </h1>


  {% for task in tasks %}
    <div style="width: 750px" class="card mb-4">
      <div class="card-header mb-0">
        <div class="row">
          <h5 class="d-flex">{{ task.content }}
          {% if not task.is_completed %}
            <span class="badge bg-danger mx-4">Not done</span>
          {% else %}
            <span class="badge bg-success mx-4">Done</span>
          {% endif %}
          </h5>
          <div class="text-right mt-n5">
            {% if task.is_completed %}
              <a class="btn bg-gradient-light" href="{% url 'tasks:task-toggle' pk=task.id %}">Undo</a>
            {% else %}
              <a class="btn bg-gradient-success" href="{% url 'tasks:task-toggle' pk=task.id %}">Complete</a>
            {% endif %}
          </div>
        </div>

      </div>
      <div class="card-body mt-n4">
        <p class="text-xs">Created: {{ task.datetime }}</p>
        {% if task.deadline %}
          <p class="text-xs text-danger">Deadline: {{ task.deadline }}</p>
        {% endif %}
      </div>
      <div class="card-footer mt-n5">
        <div class="row">
          <p> Tags:
            {% for tag in task.tags.all %}
              <span class="badge bg-info pt-1">{{ tag.name }}</span>
            {% endfor %}
          </p>
          <div class="text-right mt-n5">
            <a class="btn bg-gradient-white" href="{% url 'tasks:task-update' pk=task.id %}">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
              </svg>
            </a>
            <a class="btn bg-gradient-white" href="{% url 'tasks:task-delete' pk=task.id %}">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z"/>
                <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z"/>
              </svg>
            </a>
          </div>
        </div>
      </div>
    </div>
  {% empty %}
    <p>There are no tasks for today!</p>
  {% endfor %}
  {% endblock %}

templates/tasks/tag_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <div class="card mt-8 col-md-10 px-6 py-8">
      <div class="container">
        <h2 class="mb-4">Delete <i>"{{ tag.name }}" tag?</i></h2>
        <p> Are you sure, you want to delete the tag - <i><strong>{{ tag.name }}?</strong></i></p>
        <p class="mb-6"><strong style="color: red">Warning!</strong> You won't be able to restore lost information!</p>
        <form action="" method="post">
          {% csrf_token %}
          <input type="submit" value="Confirm" class="btn bg-gradient-success mx-auto">
          <a class="btn bg-gradient-danger mx-4" href="{% url 'tasks:tag-list' %}">Cancel</a>
        </form>
      </div>
    </div>

{% endblock content %}

templates/tasks/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h2 class="mt-8 mx-6">{{ object|yesno:"Update,Create" }} tag</h2>
  <div class="card col-md-10">
    <form class="px-6 py-5" action="" method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit" value="Submit" class="btn bg-gradient-success mt-3">
      <a class="btn bg-gradient-secondary mt-3" href="{% url 'tasks:tag-list' %}">Cancel</a>
    </form>
  </div>
{% endblock %}

templates/tasks/tag_list.html
{% extends "base.html" %}

{% block content %}
  <div class="row d-flex">
    <h1 class="mb-5 mt-6 text-secondary">Tags</h1>
    <div class="text-right mt-n7">
      <a class="btn bg-gradient-info mt-2 " href="{% url 'tasks:tag-create' %}">Add tag</a>
    </div>
  </div>

  <table class="table text-center">
    <thead>
    <tr>
      <th class="col">Name</th>
      <th class="col">Update</th>
      <th class="col">Delete</th>
    </tr>
    </thead>
    <tbody>
    {% for tag in tag_list %}
      <tr>
        <td><p class="mt-3"> {{ tag.name }} </p></td>
        <td>
          <a class="btn bg-gradient-white my-2" href="{% url 'tasks:tag-update' pk=tag.id %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
              <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
            </svg>
          </a>
        </td>
        <td>
          <a class="btn bg-gradient-white my-2" href="{% url 'tasks:tag-delete' pk=tag.id %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
              <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z"/>
              <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z"/>
            </svg>
          </a>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/tasks/task_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <div class="card mt-8 col-md-10 px-6 py-8">
      <div class="container">
        <h2 class="mb-4">Delete <i>"{{ task.content }}" task?</i></h2>
        <p> Are you sure, you want to delete the team - <i><strong>{{ task.content }}?</strong></i></p>
        <p class="mb-6"><strong style="color: red">Warning!</strong> You won't be able to restore lost information!</p>
        <form action="" method="post">
          {% csrf_token %}
          <input type="submit" value="Confirm" class="btn bg-gradient-success mx-auto">
          <a class="btn bg-gradient-danger mx-4" href="{% url 'tasks:index' %}">Cancel</a>
        </form>
      </div>
    </div>

{% endblock content %}

templates/tasks/task_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <h2 class="mt-8 mx-6">{{ object|yesno:"Update,Create" }} task</h2>
  <div class="card col-md-10">
    <form class="px-6 py-5" action="" method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit" value="Submit" class="btn bg-gradient-success mt-3">
      <a class="btn bg-gradient-secondary mt-3" href="{% url 'tasks:index' %}">Cancel</a>
    </form>
  </div>
{% endblock %}